apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/vsrekul/docker-development-youtube-series
 # secretRef:
    #name: example-app-2-github